### ISSUE TITLE
Missing type:array in response body demo

### ISSUE THREAD

**Issue by postatum** [raml-org/webapi-parser#19]
> did you notice that `type: array` is missing here[1]. Seems like AMF considers is valid though. Weird. Can you check if there is TCK test for this? If not can you add one or an issue if you don't want to do it now.
[1] https://github.com/raml-org/webapi-parser/blame/master/docs/resolving.md#L66

**Comment by postatum** [comment]
Added an example https://github.com/raml-org/raml-tck/commit/38f29cd66066ad23c77a407e5073828aa6dba05e

**Comment by postatum** [comment]
Also created an issue in amf https://github.com/aml-org/amf/issues/524

**Comment by HugaertsDries** [comment]
Has this issue been resolved? Because when I build an `ArrayShape` and add items to it, `type: array` is still missing.
```
ArrayShape arrayShape = new ArrayShape(); 
arrayShape.withItems(new ScalarShape().withDataType("http://www.w3.org/2001/XMLSchema#string"));
```
output:
```
items:
   type: string
```
