### ISSUE TITLE
Revisit JS docs

### ISSUE THREAD

**Issue by postatum** [raml-org/webapi-parser#23]
Find something simpler in terms of look and feel

**Comment by jstoiko** [comment]
- look into “minimal” theme of typedoc[1] 
- look into TSDoc[2] 
- any other option?

[1] https://github.com/TypeStrong/typedoc/blob/master/README.md
[2] https://github.com/microsoft/tsdoc

**Comment by postatum** [comment]
@jstoiko I've reworked docs generation a little in `i23_revisit_js_docs` branch. Please run `./scripts/generate-js-docs.sh` and let me know how you like it.
It now merges amf and webapi-parser declarations into one file and excludes external libs from the output.

**Comment by nkuehn** [comment]
Hi, some user feedback:  The specific visual layout is verbose, that's right.  But my actual problem with the documentation is that it does not seem to contain a lot of actual documentation (i.e. explanation or definition or guidance) beyond the raw API surface. 

I can't really find any descriptions beyond the occasional tautology "findByType:  Finds by Type":  

In other words:  The signal-to-noise ratio is very low.  Lowering the "noise" with a simpler visual theme is useful but if there is so little relevant signal it's still mostly "noise".  So investing more time into actual writing beyond the example code would help the docs more than a different theme.

**Comment by postatum** [comment]
Understood. Thanks a lot for the feedback @nkuehn !
