### ISSUE TITLE
ClientList[Example] is empty all the time

### ISSUE THREAD

**Issue by peter-hazell** [raml-org/webapi-parser#34]
The ClientList[Example] is empty all the time when I try to use request/response examples that have been parsed from the RAML. The RAML is valid and when debugging I can see that it has correctly parsed the examples, but when trying to access through the WebApi object, the example lists are always empty.

**Comment by postatum** [comment]
Hi @peter-hazell . Please provide RAML doc you parse and the code snipped you parse it with.

**Comment by peter-hazell** [comment]
Hi @postatum 

See below:

RAML:
`#%RAML 1.0
title: Test API
version: 1.0
protocols: [ HTTPS ]
baseUri: https://test.com

mediaType: [ application/json, application/hal+json ]

/test/test-raml-service/testing/{id}:
  uriParameters:
    id:
      description: The unique test ID
      type: string
      example: ABC123
  get:
    displayName: Get test information
    description: Retrieves a test value for testing purposes
    queryParameters:
      testName:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            type: !include ../test-raml/schemas/test.json
            example: !include ../test-raml/examples/test.json`

test JSON example:
`{
  "testValue": 50
}`

test JSON schema:
`{
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "The test schema",
  "properties": {
    "testValue": {
      "type": "number",
      "description": "The test value that is returned"
    }
  },
  "required": [
    "testValue"
  ]
}`

Code to demonstrate the problem I am experiencing:
`val apiBaseUnit: WebApiBaseUnit = Raml10.parse("file://test-raml/test-raml.raml").get
    val apiDocument: WebApiDocument = apiBaseUnit.asInstanceOf[WebApiDocument]
    val api: WebApi = apiDocument.encodes.asInstanceOf[WebApi]

    //Response examples
    api.endPoints.forEach(endpoint =>
      endpoint.operations.forEach(operation =>
        operation.responses.forEach(response =>
          println(response.examples.size()) // Seems to always be 0, which indicates the list is always empty and the response examples aren't being picked up
        )
      )
    )

    //Response payload examples
    api.endPoints.forEach(endpoint =>
      endpoint.operations.forEach(operation =>
        operation.responses.forEach(response =>
          response.payloads.forEach(payload =>
            println(payload.examples.size())) // Also 0
        )
      )
    )

    //URI Parameter examples
    api.endPoints.forEach(endpoint =>
      endpoint.parameters.forEach(parameter =>
        println(parameter.examples.size()) // Also 0, which indicates it's not picking up the URI parameter example either
      )
    )

    //Schema
    api.endPoints.forEach(endpoint =>
      endpoint.operations.forEach(operation =>
        operation.responses.forEach(response =>
          response.payloads.forEach(payload =>
            println(payload.schema.asInstanceOf[NodeShape].toJsonSchema)) // No issue getting the response schema
        )
      )
    )`

**Comment by peter-hazell** [comment]
Hi @postatum 

See below:

**RAML**
```
#%RAML 1.0
title: Test API
version: 1.0
protocols: [ HTTPS ]
baseUri: https://test.com

mediaType: [ application/json, application/hal+json ]

/test/test-raml-service/testing/{id}:
  uriParameters:
    id:
      description: The unique test ID
      type: string
      example: ABC123
  get:
    displayName: Get test information
    description: Retrieves a test value for testing purposes
    queryParameters:
      testName:
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            type: !include schemas/test-schema.json
            example: !include examples/test-example.json
```

**test-schema.json**
```
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "The test schema",
  "properties": {
    "testValue": {
      "type": "number",
      "description": "The test value that is returned"
    }
  },
  "required": [
    "testValue"
  ]
}
```

**test-example.json**
```
{
  "testValue": 50
}
```

**Code to demonstrate the issue**
```
 val apiBaseUnit: WebApiBaseUnit = Raml10.parse("file://test-raml/test-raml.raml").get
    val apiDocument: WebApiDocument = apiBaseUnit.asInstanceOf[WebApiDocument]
    val api: WebApi = apiDocument.encodes.asInstanceOf[WebApi]

    //Response examples
    api.endPoints.forEach(endpoint =>
      endpoint.operations.forEach(operation =>
        operation.responses.forEach(response =>
          println(response.examples.size()) // Seems to always be 0, which indicates the list is always empty and the response examples aren't being picked up
        )
      )
    )

    //Response payload examples
    api.endPoints.forEach(endpoint =>
      endpoint.operations.forEach(operation =>
        operation.responses.forEach(response =>
          response.payloads.forEach(payload =>
            println(payload.examples.size())) // Also 0
        )
      )
    )

    //URI Parameter examples
    api.endPoints.forEach(endpoint =>
      endpoint.parameters.forEach(parameter =>
        println(parameter.examples.size()) // Also 0, which indicates it's not picking up the URI parameter example either
      )
    )

    //Schema
    api.endPoints.forEach(endpoint =>
      endpoint.operations.forEach(operation =>
        operation.responses.forEach(response =>
          response.payloads.forEach(payload =>
            println(payload.schema.asInstanceOf[NodeShape].toJsonSchema)) // No issue getting the response schema
        )
      )
    )
```

**Comment by postatum** [comment]
Thank you @peter-hazell
I've reported this issue in our dependency project.

**Comment by peter-hazell** [comment]
Thank you!

**Comment by postatum** [comment]
Hi @peter-hazell 

Your question has been answered - https://github.com/aml-org/amf/issues/546#issuecomment-519947579

Let us know if that solves your issue.

**Comment by peter-hazell** [comment]
Hi @postatum apologies if I'm missing something.. examples does not seem to be part of the schema model as per the comment.. schema is of type `Shape`

**Comment by postatum** [comment]
> Hi @postatum apologies if I'm missing something.. examples does not seem to be part of the schema model as per the comment.. schema is of type `Shape`

@peter-hazell from what I see from schema id, it's a [ScalarShape](https://raml-org.github.io/webapi-parser/js/classes/_amf_client_js_.model.domain.scalarshape.html) which inherits Shape as Shape > AnyShape > ScalarShape.

**Comment by peter-hazell** [comment]
Ah ok yes - I have got it working now using examples from `NodeShape`.  Thanks for you help. Feel free to close this issue now.

**Comment by postatum** [comment]
@peter-hazell you are welcome :hand:
