### ISSUE TITLE
Convert .raml to json

### ISSUE THREAD

**Issue by wilsson** [raml-org/webapi-parser#36]
How can i convert my .raml to json

using `raml-1-parser` was like that:

```
const raml = require("raml-1-parser");
const path = require("path");
const fs = require('fs');

const apiJSON = raml.loadApiSync(path.resolve(__dirname, "./api.raml"));
console.log(JSON.stringify(apiJSON, null, 2));

fs.writeFileSync('./api.json', JSON.stringify(apiJSON, null, 2), 'utf-8')
```

with `webapi-parser` how would it be?

**Comment by postatum** [comment]
Hi @wilsson
You can convert *RAML Data Types* to *JSON Schema* as demonstrated in [this example](https://github.com/raml-org/webapi-parser/blob/master/examples/js/ramldt-jsonschema.js).

Also you can convert a complete API to OAS 2.0 or JSON-LD Graph like so:

```js
const wap = require('webapi-parser').WebApiParser
const path = require("path");

async function main () {
  const ramlPath = `file://${path.resolve(__dirname, "./api.raml")}`
  const ramlModel = await wap.raml10.parse(ramlPath)
  const apiJSON = await wap.oas20.generateString(ramlModel)

  fs.writeFileSync('./api.json', JSON.stringify(apiJSON, null, 2), 'utf-8')
}

main()
```

**Comment by wilsson** [comment]
I liked the solution for API to OAS 2.0.
But how would you just convert it to JSON without using oas20 ?

**Comment by postatum** [comment]
> I liked the solution for API to OAS 2.0.
> But how would you just convert it to JSON without using oas20 ?

I'm afraid there's no way to convert yaml object to json object and keep it a RAML 1.0 using webapi-parser.

**Comment by postatum** [comment]
@wilsson by the way, you can also convert RAML 1.0 to JSON-LD. We've seen at least one other project replacing the JSON output of the legacy JS parser by our JSON LD output, so this may help.

It's similar to using oas20, but this time it's `wap.amfGraph`:
```js
const wap = require('webapi-parser').WebApiParser
const path = require("path");

async function main () {
  const ramlPath = `file://${path.resolve(__dirname, "./api.raml")}`
  const ramlModel = await wap.raml10.parse(ramlPath)
  const apiJSON = await wap.amfGraph.generateString(ramlModel)

  fs.writeFileSync('./api.json', JSON.stringify(apiJSON, null, 2), 'utf-8')
}

main()
```
---
PS. If you only need a RAML doc represented as a JS/JSON object, you can also use [js-yaml](https://github.com/nodeca/js-yaml#api) which would parse RAML into a JS object.

**Comment by wilsson** [comment]
I wanted a simpler structure to do something similar to `raml2html` since they use raml-1-parser and it is deprecated.

Thanks for the help
