### ISSUE TITLE
PayLoad class examples() method returning empty list while parsing RAML using webapi-parser

### ISSUE THREAD

**Issue by anilmanchala07** [raml-org/webapi-parser#38]
We are trying to parse a small RAML file using new webapi-parser. When we are trying to read an example from the response(payload)  we are getting the empty list as a response. 

Please find the file content below

**#%RAML 0.8
title: Helloworld
version: 0.8
baseUri: http://www.helloworld.com/myapi/{version}

/helloWorld:
 get:
    description: returns default hello world
    responses:
          200:
            body:
              application/json:
               example: |
                  {
                         “returnMessage”:“helloReturn”
                  }**
 
As the raml-java-parser is deprecated we are planning to migrate to new webapi- parser and this seems to be a blocker.

**Comment by postatum** [comment]
Hi @anilmanchala07

Here's how you get example from your RAML doc. It's js-pseudo-code, but I believe you can easily translate it to Java.
```
model = <parse raml doc>
model.encodes.endPoints[0].operations[0].responses[0].payloads[0].schema.examples[0].value.value()
        ^           ^          ^             ^              ^        ^        ^        ^--------^
       API    /helloWorld     get           200   application/json schema    1st ex  its string value
```

API Doc: https://raml-org.github.io/webapi-parser/js/classes/_amf_client_js_.model.domain.payload.html#examples

**Comment by postatum** [comment]
Let us know if you have more questions.

**Comment by anilmanchala07** [comment]
Hi @postatum 

Thank you for the quick response. 

Payload does not have any schema variable, we have only the schema method (schema () ).
However, schema() (of type **Shape**) does not have examples() method.

We also tried using examples() method of Payload from the responses().
Even that did not work. 

Attached screen shot 
<img width="972" alt="Payload Example " src="https://user-images.githubusercontent.com/19778601/63919792-11bed880-ca5d-11e9-9a5a-87db6c90224d.png">

**Comment by postatum** [comment]
@anilmanchala07 
> Payload does not have any schema variable, we have only the schema method (schema () ).

Right, it's a variable in JS and a method in Java.

>  However, schema() (of type Shape) does not have examples() method.

`Shape` is a parent type for a few other types. Try converting it to [`NodeShape`](https://raml-org.github.io/webapi-parser/js/classes/_amf_client_js_.model.domain.nodeshape.html) and you'll get `examples()` method.

**Comment by anilmanchala07** [comment]
@postatum 
Thanks for the info. After converting to AnyShape, we are able to get the example value.

I see some other Classes which implements the Shape interface.  
like 
PropertyShape
AnyShape
RecursiveShape

Do we have any java documentation in what scenario which one to use? if there is cold you please help with info

**Comment by postatum** [comment]
@anilmanchala07 I've created an issue to ask this question in AMF project because we use customized version of their model/API. You might want to follow discussion there: https://github.com/aml-org/amf/issues/552

**Comment by anilmanchala07** [comment]
@postatum 

Could you please guide us on reading a few entries from attached RAML. like BaseUriParamaters, headers. We are able to fetch Endpoint URI parameters but  not finding a way to read Base Uri parameters. 
Could you please share all reference, links or documents on this. Also, it would be helpful if share implementation comments of method and classes (even if it is other than java ) 

Here is RAML file we are parsing 
========================
#%RAML 1.0
title:
    value: api title
    (basic): title
description: api description
version: 1.0
baseUri: http://base.uri/{version}/{param1}/{param2}/{param3}/{param4}
mediaType: application/json
protocols: [HTTP, HTTPS]

baseUriParameters:
    param1:
        displayName: Param 1
        description: some description
        type: string
        maxLength: 10
        example: one
    param2?:
        type: string
    param3?:
        type: string
        required: true
    param4?:
        type: string
        required: false

documentation:
    - title: doc title 1
      content:
        value: single line
        (basic): first chapter
    - title: doc title 2
      content: |
           multi
           line

types:
    User:
        type: object
        properties:
            firstname: string
            lastname: string
            age:
                type: integer
                minimum: 0
                maximum: 144
            height?: number
            goggles?: boolean
        default: {"firstname": "pietro", "lastname": "maximoff", "age": 104, "height": 1.563, "goggles": true}
        examples:
            batman:
                firstname: bruce
                lastname: wayne
                age: 77
                height: 1.82
            daredevil:
                firstname: matt
                lastname: murdock
                age: 52
            quicksilver: |
                {"firstname": "pietro",
                 "lastname": "maximoff",
                 "age": 104,
                 "height": 1.563,
                 "goggles": true}
    SuperUser:
        type: User
        properties:
            skills:
                type: string[]
                maxItems: 3
    Users:
        type: User[]
        default: [{"firstname": "pietro", "lastname": "maximoff", "age": 104, "height": 1.563, "goggles": true},{"firstname": "lionel", "lastname": "messi", "age": 30, "height": 1.7, "goggles": false}]
        minItems: 2
    nString:
        maxLength: 10
    UserJson: |
        {
         "$schema": "http://json-schema.org/draft-04/schema",
         "type": "object",
         "properties": {
           "firstname":  { "type": "string" },
           "lastname":  { "type": "string" },
           "age":  { "type": "integer" }
         },
         "required": [ "firstname", "lastname" ]
        }
    UserXml: |
        <xs:schema attributeFormDefault="unqualified"
                  elementFormDefault="qualified"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema">
         <xs:element name="api-request">
           <xs:complexType>
             <xs:sequence>
               <xs:element type="xs:string" name="input"/>
             </xs:sequence>
           </xs:complexType>
         </xs:element>
        </xs:schema>
    TypeWithCustomFacets:
        type: string
        facets:
            facet1?: integer
            facet2?:
                type: integer
            facet3?:
                type: integer
                required: true
            facet4?:
                type: integer
                required: false

traits:
    traitOne:
        displayName: uno
        description: method description
        usage: late night
    traitTwo:
        displayName: dos
        description: <<text>>

resourceTypes:
    first:
        usage: first usage

securitySchemes:
  oauth_2_0:
    displayName: OAuth2
    description: oauth 2.0
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
             Used to send a valid OAuth 2 access token. Do not use
             with the "access_token" query string parameter.
          type: string
      queryParameters:
        access_token:
          description: |
             Used to send a valid OAuth 2 access token. Do not use with
             the "Authorization" header.
          type: string
      responses:
        401:
          description: |
              Bad or expired token. This can happen if the user or Dropbox
              revoked or expired an access token. To fix, re-authenticate
              the user.
        403:
          description: |
              Bad OAuth request (wrong consumer key, bad nonce, expired
              timestamp...). Unfortunately, re-authenticating the user won't help here.
    settings:
      authorizationUri: https://www.dropbox.com/1/oauth2/authorize
      accessTokenUri: https://api.dropbox.com/1/oauth2/token
      authorizationGrants: [ authorization_code, implicit ]
  oauth_1_0:
    description: OAuth 1.0 continues to be supported
    type: OAuth 1.0
    settings:
      requestTokenUri: https://api.dropbox.com/1/oauth/request_token
      authorizationUri: https://www.dropbox.com/1/oauth/authorize
      tokenCredentialsUri: https://api.dropbox.com/1/oauth/access_token
      signatures: [ 'HMAC-SHA1', 'PLAINTEXT' ]

securedBy: [oauth_2_0, oauth_1_0, null]

annotationTypes:
  basic:
    type: string
  complex:
    allowedTargets: [ API, Resource ]
    properties:
      controls:
        description: where is hypermedia
        properties:
          url?:
            default: href
          property:
          names:
            type: string[]
      permanentUri?:
        type: boolean
        default: true

(basic): sometimes

(complex):
    controls:
        url: here
        property: off
        names: [one, two]
    permanentUri: false

/top:
    description: top description
    type: first
    is: ["traitOne", {"traitTwo": {"text": "hola"}}]
    get:
        description: get something
        protocols: HTTPS
        securedBy: oauth_2_0
        queryParameters:
            one:
                displayName: The One
                type: number
            two:
                type: (string|number)[]
            three?: integer
            four?:
                type: integer
            five?:
                type: string
                required: true
            six?:
                type: string
                required: false
        headers: &headersGet
            one:
            two:
                displayName: The Second
    post:
        description: post something
        is:
          traitTwo:
                text: picky
        queryString:
            properties:
                lat: number
                long: number
        body: &bodyPost
            application/json:
                default: {"firstname": "pietro", "lastname": "maximoff", "age": 104, "height": 1.563, "goggles": true}
                type: User
                example: |
                    {
                        "firstname": "tato",
                        "lastname": "bores",
                        "age": 66
                    }
            application/xml:
                schema: |
                  <?xml version="1.0" encoding="utf-16"?>
                  <xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" version="1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                    <xsd:element name="first" type="xsd:string" />
                    <xsd:element name="second" type="xsd:string" />
                  </xsd:schema>
                examples:
                    first: |
                        <first/>
                    second: |
                        <second/>
        responses:
            200:
                body: *bodyPost
                headers: *headersGet
            400:
                body:
                    text/plain: ~


    /child/{childId}:
        securedBy: [oauth_2_0, oauth_1_0, null]
        description: child description
        uriParameters:
            childId?:
                type: integer
            childId2?:
                required: true
        post:
            body:
                schema: UserJson
=================================
