### ISSUE TITLE
Do traits resolve?

### ISSUE THREAD

**Issue by earniedyke** [raml-org/webapi-parser#39]
I am trying to parse the attached RAML in which I am employing Traits but when I execute .resolve() I do not see the request payload. Are traits being resolved in the current version of the parser?

Earnie!
[api.txt](https://github.com/raml-org/webapi-parser/files/3617728/api.txt)

**Comment by postatum** [comment]
Hi Earnie!

Here's a JS code I ran [1] with a simplified example of you API doc [2]. And in my case trait was resolved.

Please answer there questions so I could help you:
1. Do you use webapi-parser with JS or Java?
2. Please provide a code snippet.
3. What do you mean by "I do not see the request payload"? Do you mean you can't access it through the "WebApi" Model?

**Comment by earniedyke** [comment]
Thanks for the quick response! I am using the Java version and am trying to parse the RAML then iterate over each endpoint and get the properties for the request (if any) and any responses. Here is some code I have been using in an attempt to understand the object model:

```
public class RamlInteregator {
    public List<Pojo> interogate(File raml) throws Exception {
        List<Pojo> pojos = new ArrayList<>();
        if (raml == null) {
            throw new IllegalArgumentException("RAML file is required");
        }
        if (!raml.exists()) {
            throw new IllegalArgumentException(raml.toString() + " not found");
        }
        WebApiBaseUnit model = Raml10.parse(raml.toURI().toString()).get();
        WebApiDocument resolved = (WebApiDocument) Raml10.resolve(model).get();
        WebApi api = (WebApi) resolved.encodes();
        for (EndPoint ep : api.endPoints()) {
            System.out.println("EP: " + ep.path());
            for (Operation op : ep.operations()) {
                System.out.println("\t" + op.method().value());
                System.out.println("\t\t" + op.request().payloads().size());
                op.request().payloads().forEach(py -> {
                    System.out.println("\t\t\t" + py.mediaType().value());
                    py.graph().properties().forEach(p -> System.out.println("\t\t\t\t" + py.graph().getObjectByPropertyId(p).forEach(prop-> System.out.println(prop.));));
                });
            }
        }
        System.out.println("-----");
        return pojos;

    }
}
```
Earnie!

**Comment by earniedyke** [comment]
Please note the code I posted will not compile. I copied it in the middle of make some changes but the idea is the same.

Earnie!

**Comment by postatum** [comment]
Hi Earnie.

Try doing `py.schema().properties()` instead of `py.graph().properties()`. This will give you an array of [PropertyShape](https://raml-org.github.io/webapi-parser/js/classes/_amf_client_js_.model.domain.propertyshape.html)s. These have useful fields like `name`, `range`, `range().dataType()`, etc.

**Comment by postatum** [comment]
Closing as this issue seems to be resolved.
