### ISSUE TITLE
Resolve named type declarations without anonymizing them into the resource endpoints?

### ISSUE THREAD

**Issue by nkuehn** [raml-org/webapi-parser#42]
Hello, 

we're currently using the now-deprecated previous RAML parser for our documentation stack (in conjunction with the raml2obj library). 

For generating documentation we need the retain the named type declarations as such, but in a fully resolved way - i.e. keeping the type as a named type, but in its effective API surface form with traits, overlays, inheritance, libraries etc. fully resolved. 

The code examples here all show that resolving always "anonymizes" the types into the endpoints, but that would make the generated documentation not very useful any more (esp. very repetitive). 

Is there a way to selectively resolve the types without losing them as named types? 

Thanks  for any help!

**Comment by postatum** [comment]
Hi @nkuehn. 

You can use undocumented internals for now to make resolved RAML look the way you expect to.
**Note that these internals may change at some point in the future**.

We'll consider making this an official and user-friendly API.

```js
const lib = require('webapi-parser') // Note the root lib import

const resolver = lib.Resolver('RAML 1.0')
const resolved = resolver.resolve(model, 'editing') // Note the 'editing' argument
```

**Comment by jhorst11** [comment]
@postatum using the `editing` field allows us to keep the types node but it still resolves the types in the resource endpoints.. is there a way to keep them as references?

**Comment by davidturissini** [comment]
@postatum this is a great find, thank you! 

> We'll consider making this an official and user-friendly API.

It would be great if this were a first-class API. We are building client-side REST api clients that use RAML to generate normalization code. AMF is not available on Swift or Kotlin at this time, so our solution is to deliver a "merged" RAML file to these environments so we do not have to hand roll our own resolution on the client. Having a first-class supported API for this would be extremely helpful.

**Comment by postatum** [comment]
> @postatum using the `editing` field allows us to keep the types node but it still resolves the types in the resource endpoints.. is there a way to keep them as references?

Sorry, there's currently no way to do that.

**Comment by nkuehn** [comment]
OK, thanks for all the help.  I'll consider holding both a resolved and unresolved version in memory in parallel to be able to have the named type on the resource endpoint and then find the fully resolved type in the resolved-with-editing-flag instance.  

Not a beauty but the old parser worked similarly, having to hand-pick topics from the expanded/resolved/runtime perspective and the raw declaration, hoping you don't miss some edge case.

**Comment by nkuehn** [comment]
Hi, update from the state of my tech exploration implementation:  resolving with "editing" works fine and keeps the named type declarations. 

But I found a more fundamental issue that's a variation of @jhorst11 's question:  On the endpoints, the references to the named types are completely lost even _without_  calling `resolve()`,  only parsing the RAML and then using "generateFile" already flattens the body types into the resource endpoints.  

That's a blocker for our needs, trying the collect that information from the raw RAML on YAML level manually is not a viable option. 

Any Ideas? Would programmatic navigation through the model help?

**Comment by postatum** [comment]
@nkuehn, yes, programmatic navigation through the model should help. When you resolve the model, names of declared types are still in there - at the places if their application. E.g.

```js
const wap = require('webapi-parser').WebApiParser

ramlStr = `#%RAML 1.0
title: API with Types
types:
  User:
    type: object
    properties:
      firstName: string
      lastName:  string
      age:
        type: integer
        minimum: 0
        maximum: 125
/users/{id}:
  get:
    responses:
      200:
        body:
          application/json:
            type: User

`

const model = await wap.raml10.parse(ramlStr)
const resolved = await wap.raml10.resolve(model)

const payload = resolved.encodes.endPoints[0].operations[0].responses[0].payloads[0]
const typeName = payload.schema.name.value()

console.log(resolved.declares.length)
// >> 0
console.log(typeName)
// >> 'User'
```

**Comment by nkuehn** [comment]
Nice, thank you so much for the fast response! 

I'll brainstorm a bit how to continue since I'd like to stick with RAML as the external facade of the system since all the users and devs know it by heart.   Maybe I'll add the declared type as an overlay with annotations to the resolved type in a preprocessing step or something like that.  RAML is fortunately expressive enough to not invent a custom format to retain some additional information.

**Comment by nkuehn** [comment]
Update: I was sucessful in reading all the needed information but fail on performance now.  So I think we can close this issue (from my perspective) or you choose to keep it open as a tracker to make the "editable" flag official.
