### ISSUE TITLE
How to use Nested resources when building a RAML webapi

### ISSUE THREAD

**Issue by KoenDaelman** [raml-org/webapi-parser#43]
Hello,

I'm trying to build a RAML 1.0 API from scratch and writing it to a file using the provided example code. The issue I'm having is that I can't figure out how to add nested resources to the document. When adding an `EndPoint` to the `WebApi` object it is always treated as a top-level resource. Is this a bug or is there a way to set the parent of an `EndPoint`.  

For example this is the output when running the Raml10Building.buildApi() demo. The `/{id}` resource should be a nested resource of `/users`.

```
#%RAML 1.0
title: Foo org API
baseUri: https://api.spotify.com/v/{version}
description: Describes Foo org API
mediaType:
  - application/json
version: "1.1"
protocols:
  - http
  - https
/users:
  displayName: Users endpoint
  description: Lists users
  get:
    displayName: GET Users
    description: Get Several Users
    queryParameters:
      ids:
        description: A comma-separated list of IDs
        type: string
    responses:
      "500":
        body:
          text/plain:
            type: string
      "200":
        body:
          application/json:
            properties:
              username:
                type: string
              email:
                type: string
/users/{id}:
  displayName: User endpoint
  description: Get user

```

**Comment by postatum** [comment]
Hi @KoenDaelman. Sorry it took me so long to answer your question.

Currently there's no way to produce RAML like 
```raml
/users:
    /{userId}:
```
only
```raml
/users:
/users/{userId}:
```

I understand it may be inconvenient, but note that both ways of defining nested resources are valid [according to RAML 1.0 spec](https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/#resources-and-nested-resources):
>For example, if /bom is itself a resource, then /items SHOULD be a nested resource of /bom, versus using /bom/items as a non-nested resource.
