### ISSUE TITLE
Track File inclusions or configure custom file loader

### ISSUE THREAD

**Issue by nkuehn** [raml-org/webapi-parser#45]
Hi, 

the previous RAML Javascript parser had the ability to configure a custom file loader which allowed us to implement hot-reloading during API documentation authoring because our implementation "knew" exactly what files were included by the parser and could trigger a reload of the right API root file. 

Is there a way to achieve a similar goal?  E.g. by exposing the included paths or configuring a file loader? 

Thanks for any hints!

**Comment by postatum** [comment]
Hi @nkuehn.

There's currently no way to do it using official `webapi-parser` API. Though you can define a custom file loading using internals (see code below).

We'll consider making this an official API.

```js
const lib = require('webapi-parser')

const ramlStr = `
  #%RAML 1.0
  title: API with Types
`

async function main () {
  const FileLoader = {
    fetch: function (resource) {
      return new Promise(function (resolve, reject) {
        if (resource.endsWith('foo.raml')) {
          resolve(new lib.client.remote.Content(ramlStr, resource))
        } else {
          reject(new lib.ResourceNotFound('File cannot be found'))
        }
      })
    },
    accepts: function (resource) {
      console.log('I am acceptings things')
      return true
    }
  }
  let env = new lib.client.environment.Environment()
  env = env.addClientLoader(FileLoader)

  const parser = new lib.Raml10Parser(env)
  await lib.WebApiParser.init()
  const model = await parser.parseFileAsync('http://hello.hi/foo.raml')
  console.log(model.raw)
}

main()
```

**Comment by nkuehn** [comment]
Thanks!  we'll give it a try once we have all the ends together that make it theoretically work at all, which is starting to look better due to your help.

**Comment by postatum** [comment]
> Thanks! we'll give it a try once we have all the ends together that make it theoretically work at all, which is starting to look better due to your help.

Good. I'll close this issue for now. Feel free to reopen it if you need more help!
