### ISSUE TITLE
Add a documentation for API Console resolution

### ISSUE THREAD

**Issue by jarrodek** [raml-org/webapi-parser#49]
In the documentation: https://raml-org.github.io/webapi-parser/resolving.html
there are examples of working with the model but it is missing a use case of API Console that uses the resolution pipeline created for it.

**Comment by postatum** [comment]
@jarrodek hi. What resolution pipeline do you mean?

**Comment by jarrodek** [comment]
Like this: https://github.com/mulesoft/api-console/blob/6.0.0-preview/demo/demo-server/api/amf-service/amf-parser.js#L50
The editing pipeline was introduced for API Console to have all types resolved when model is generated.

**Comment by postatum** [comment]
Oh I see. Editing pipeline isn't currently available via webapi-parser.

**Comment by postatum** [comment]
This feature was implemented in https://github.com/raml-org/webapi-parser/pull/78 and should be released in some time.
