### ISSUE TITLE
How to constuct a Uri/Path parameter.

### ISSUE THREAD

**Issue by HugaertsDries** [raml-org/webapi-parser#50]
Hello there!

I'm trying to build a RAML 1.0 "WebApi" model from scratch. But I don't seem to be able to create Uri/Path parameters.

When I try to add the uri-parameters to the `Endpoint` class using the `withParameter()`, I get the following output.
```
  (amf-parameters):
    -
      name: id
      type: integer
```
When I try using the provided function `withUriParameter()` on the `Request` class, I get the following output.
```
 (amf-baseUriParameters):
      id:
        type: integer
```
Could it be possible to add an example to the `Raml10Building.java` ? 
Or is this not yet supported?

Thx in advance!

**Comment by postatum** [comment]
Hi @HugaertsDries. I've directed your question of our dependency project. Please follow this issue to get a a response. https://github.com/aml-org/amf/issues/563
