### ISSUE TITLE
Information section of YAML not converting?

### ISSUE THREAD

**Issue by TravelersInsuranceDev** [raml-org/webapi-parser#53]
Hello. I am a developer at Travelers Insurance and we would like to utilize your solution to convert our yaml files to raml. For the most part it seems to be working correctly, but it is not generating the information sections as follows:

info: 
  title: 
  description: 
  version: 
  contact:
    name: 
    url: 
    email: 
host: 
basePath: 
produces: 
  - 'application/json'
consumes: 
  - 'application/json'

We are using the code in the following manor:
const inPath = path.join(__dirname, '../../../spec/swagger.yaml')
  const model = await wap.oas20.parseYaml(`file://${inPath}`)
  const convertedString = await wap.raml10.generateString(model)

Any help will be appreciated! :)

**Comment by postatum** [comment]
Hi @TravelersInsuranceDev.

Please provide:
1. Yaml file you use;
2. Output raml string you get;
3. Raml string you expect to be produced (or describe it).

Thank you!

**Comment by postatum** [comment]
Closing as there was no answer for a long time. Feel free to reopen if the issue still occurs.
