### ISSUE TITLE
Implement OAS 3.0 Writer

### ISSUE THREAD

**Issue by lukaslentner** [raml-org/webapi-parser#59]
Hi,

as OAS 3.0 Support gets wider and wider it would be really helpful to be able to convert from raml 1.0 to oas 3.0

Any plans on this? Any time perspective?

Thankx
Lukas

**Comment by postatum** [comment]
Hi @lukaslentner.

Sorry for not getting back to you on this issue. We've been working on this for some time and we've just released a new version (0.5.0) which adds Oas3 beta support.

Feel free to report any issues you face when using it.
Thanks!
