### ISSUE TITLE
OAS ignores x- prefixed annotations for properties with reference types

### ISSUE THREAD

**Issue by idr0id** [raml-org/webapi-parser#64]
### Issue

Using `org.raml:webapi-parser:0.4.0`.

Running code below should generate the same OAS specification as in input. Instead of that, the `x-nullable` definition of `group` property has been omitted.

### Code

**example.kt**

```kotlin
package co.acme.generate;

import webapi.Oas20

fun main() {
    val spec = Oas20.parseYaml("file:///path/to/swagger.yaml").get()
    println(Oas20.generateYamlString(spec).get())
}
```

**swagger.yaml**

```yaml
swagger: '2.0'
info:
  title: API
  version: '1.0'
definitions:
  Group:
    type: object
    properties:
      id:
        type: integer
  User:
    type: object
    properties:
      group:
        $ref: "#/definitions/Group"
        x-nullable: true
      age:
        type: integer
        x-nullable: true
paths:
```

**stdout**

```yaml
swagger: "2.0"
info:
  title: API
  version: "1.0"
definitions:
  Group:
    type: object
    properties:
      id:
        type: integer
  User:
    type: object
    properties:
      group:
        $ref: "#/definitions/Group"
      age:
        type: integer
        x-nullable: true
paths: {}
```

**Comment by postatum** [comment]
Hi @idr0id.

Thanks for reporting this issue. I've reported to our dependency lib: https://github.com/aml-org/amf/issues/573

**Comment by postatum** [comment]
Hi @idr0id.

According to this commend https://github.com/aml-org/amf/issues/573#issuecomment-642725505, usage of the `x-` property in your example is incorrect:

> Although the OAS 2 spec defines annotations valid at schema object level it does not define them as a valid node at Reference Object level.
> This is also invalid in JsonSchema where defining a $ref in a node makes all the other keys in the same node ignored. As Oas is based on JsonSchema we can also take this behaviour into account to determine which keys to process.

Thus I'm closing this issues. Feel free to reopen it if you have more questions.
