### ISSUE TITLE
how to convert raml to OAS3.0 with java?

### ISSUE THREAD

**Issue by abhikt48** [raml-org/webapi-parser#69]
Hi Team,

I am able to convert RAML to OAS2.0 with this parser + java. 

Can we convert to OAS3.0 as well? Could you please provide any pointer or example for converting RAML to OAS3.0?

Thanks in advance.

Regards,
Abhishek Kumar

**Comment by postatum** [comment]
Hi @abhikt48.

As you've already noticed, we are currently working on releasing OAS30 support.
To get that support early you could:
1. Clone the repo and switch to corresponding branch;
2. Build a "fat" jar as described [here](https://github.com/raml-org/webapi-parser/blob/master/CONTRIBUTING.md#generate-artifacts) or
3. Build a regular Java package and publish it to your local '.m2'.
```
sbt webapiJVM/package
sbt publishM2
```
Then you can use a package published in 3 similar to [this](https://github.com/raml-org/webapi-parser#java) but specifying `mavenLocal()` before `mavenCentral()`.

As for converting RAML to OAS30, it should work identical to RAML-OAS20, just `20`s replaced with `30`s in all the classes/objects names.

**Comment by abhikt48** [comment]
Hi @postatum , 

Thanks for update. I cloned `i59_add_oas30_support` branch and tested with both options, and having issue in both options. Please find below details.

1. package as fat JAR - i followed the above procedure to package as fat jar, but it is failling to generate FAT file. Please find attached [run_output.txt](https://github.com/raml-org/webapi-parser/files/4077044/run_output.txt).
2. packaged as JAR - I successfully packaged as jar and found breaking changes. All the parse methods returning `Promise ` scala object instead of `CompletableFuture`

  ```
 Promise<WebApiBaseUnit> parse = Oas30.parse(inp);
   Promise<WebApiBaseUnit> ramlParser = Raml10.parse(inp);
```

However, i exceuted the class with `Promise` object and started having below error. Please find below details.  Could you please help me to fix this issue.
   
 **Code** - 

   ```
 String inp ="#%RAML 1.0\n" +
	                "\n" +
	                "title: ACME Banking HTTP API\n" +
	                "version: 1.0";
	    
	    System.out.println("Input Raml10 string:\n" + inp);
	    
	    Promise<WebApiBaseUnit> ramlParser = Raml10.parse(inp);
	    
	    System.out.println("** ramlParser ** " + ramlParser);
```

**Error** - 


```
Exception in thread "main" java.lang.Error: stub
	at scala.scalajs.runtime.package$.linkingInfo(package.scala:201)
	at scala.scalajs.runtime.package$.environmentInfo(package.scala:195)
	at scala.scalajs.js.Dynamic$.global(Dynamic.scala:81)
	at amf.core.unsafe.PlatformBuilder$.isBrowser(PlatformBuilder.scala:16)
	at amf.core.unsafe.PlatformBuilder$.<init>(PlatformBuilder.scala:11)
	at amf.core.unsafe.PlatformBuilder$.<clinit>(PlatformBuilder.scala)
	at amf.core.unsafe.PlatformSecrets.$init$(PlatformSecrets.scala:16)
	at webapi.WebApiClientConverters$.<init>(ClientConverters.scala:33)
	at webapi.WebApiClientConverters$.<clinit>(ClientConverters.scala)
	at webapi.Raml10$.parse(WebApiParser.scala:81)
	at webapi.Raml10.parse(WebApiParser.scala)
	at com.ak.Test.main(Test.java:49)

```

**Comment by postatum** [comment]
Hi @abhikt48.

I'm no Java developer, but the latest log error looks weird. It looks as if it refers to a Scala version of the lib.
Can you please:
1. Delete the package you published locally to `.m2`;
2. Then rebuild it and republish again:
```sh
sbt clean
sbt webapiJVM/build
sbt webapiJVM/package
sbt publishM2
```

**Comment by abhikt48** [comment]
hi @postatum ,

I followed your suggetion and started getting below error. 
Is it possible for you to upload/release snapshot jar+pom file? This will be a great help.

**Error**
```
C:\Unknown\Git\webapi-parser-i59_add_oas30_support>sbt webapiJVM/build
[info] Loading settings for project webapi-parser-i59_add_oas30_support-build from assembly.sbt,plugins.sbt ...
[info] Loading project definition from C:\Unknown\Git\webapi-parser-i59_add_oas30_support\project
[info] Loading settings for project webapi-parser-i59_add_oas30_support from build.sbt,sonatype.sbt ...
[info] Set current project to webapi-parser (in build file:/C:/Unknown/Git/webapi-parser-i59_add_oas30_support/)
[error] Expected ':'
[error] Not a valid key: build (similar: loadedBuild)
[error] webapiJVM/build
[error]
```

**Comment by postatum** [comment]
Hi @abhikt48 .

Sorry, I gave you a wrong commands list. Process should go like

```sh
sbt clean
sbt webapiJVM/compile
sbt webapiJVM/package
sbt publishM2
```

**Comment by abhikt48** [comment]
HI @postatum 

Thanks a lot for your reply. I build successfully with above command, but staterd having same typecast issue.  All the parse methods returning `Promise ` scala object instead of `CompletableFuture`

```
Promise<WebApiBaseUnit> parse = Oas30.parse(inp);
 Promise<WebApiBaseUnit> ramlParser = Raml10.parse(inp);
```
I don't know how can i solve this :(

**Comment by postatum** [comment]
Hi again @abhikt48.

Few things:
1. Please let me know if you get the same typecasting problem when working with `Oas20` instead `Oas30`.
2. Did you try to work with promises [like so](https://github.com/raml-org/webapi-parser/blob/master/examples/java/src/main/java/co/acme/parse/Oas20Parsing.java#L18)?

**Comment by postatum** [comment]
By the way @abhikt48, we've just released version 0.5.0 which adds OAS3 support. It should soon be available on Maven Central.
If you have an existing code that uses webapi-parser, note that 0.5.0 also adds some breaking changes.

**Comment by abhikt48** [comment]
@postatum  - Thanks a lot for information. We need to use this parser in **Mule 3.8** application.  At this moment, we are in big trouble due to dependency confliction between **Mule 3.8** and **webapi-parser**. Mule 3.8 library is older than **webapi-parser** library. So i have to use **fat jar** for this scenario.  As you know that, i have trouble in generating  **fat jar** and don't know the solution as well. So could you please realese **fat jar** as well. If not in maven central, then can you release in Mule repository server or upload at github. Anything will be highly appreciated.
I am happy to raise Mulesoft support ticket as well.

Please let me know your opinion.

**Comment by postatum** [comment]
Hi @abhikt48. We are working on this issue. I'll get back to you soon.

**Comment by abhikt48** [comment]
Hi @postatum , 

Thank you so much for information. I will wait for your response.

Regards,
Abhishek Kumar

**Comment by abhikt48** [comment]
Hi @postatum  - Could you please update on this request. We are blocked at this moment. It will be great if you can release fat jar soon.

Regards,
Abhishek Kumar

**Comment by jstoiko** [comment]
@abhikt48: I am afraid we won't be releasing a "fat jar" anytime soon. Sorry if there was any confusion about that. 

Alternatively, you should be able to do build a fat jar yourself by following the steps described above by @postatum. Please make sure your local environment matches the requirements defined [here](https://github.com/raml-org/webapi-parser/blob/master/CONTRIBUTING.md#requirements).

**Comment by postatum** [comment]
Closing as the issue is stale.
