### ISSUE TITLE
Bug: Unresolved Reference while validating Raml 08 contract file if it has external schemas

### ISSUE THREAD

**Issue by sch111** [raml-org/webapi-parser#86]
**Library version used**
E.g. "0.5.0"

**Language library used with**
Java

** Description **
I was trying to validate the Raml 08/ Raml 10 contract file which were having external schema references in the same directory.

**Input**
Raml file contents which are having schema and example externally. First parsing the file using parse() method and then validating it using validate() method.

**Expected behaviour/output**
Parser should validate without throwing unresolved reference

**Comment by postatum** [comment]
Hi @sch111.

Please provide a code snippet so we could reproduce the bug.

Thanks!

**Comment by sch111** [comment]
Hi @postatum ,
Thanks for your reply. My issue got resolved. That was basically beacause of the conflicts between the dependencies in this parser and the ones that I already have. I excluded those dependencies and it worked like a charm.
Thanks!

**Comment by postatum** [comment]
> Hi @postatum ,
> Thanks for your reply. My issue got resolved. That was basically beacause of the conflicts between the dependencies in this parser and the ones that I already have. I excluded those dependencies and it worked like a charm.
> Thanks!

Cool. Glad to hear that!
